FROM node:14 as whanos-befunge

SHELL ["/bin/bash", "-c"]

ONBUILD RUN npm install befunge93

ONBUILD RUN curl -L https://gist.githubusercontent.com/Thorf1nn/e04655a186a16bab5f4f04203756c78c/raw/b680e42061b9246c213f43c2b6b85a16487b92a4/interpretor.js > /tmp/interpretor.js

ONBUILD COPY . /app

ONBUILD WORKDIR /app

CMD ["node", "/tmp/interpretor.js", "app/"]