FROM debian:latest

ONBUILD RUN apt-get update && apt-get install -y \
    g++ \
    cmake \
    make \
    && rm -rf /var/lib/apt/lists/*

ONBUILD WORKDIR /app

ONBUILD COPY . /app

ONBUILD RUN cmake . && make

ONBUILD CMD ["./CompiledApp"]