FROM python:3.12

SHELL ["/bin/bash", "-c"]

ONBUILD COPY . /app

ONBUILD WORKDIR /app

ONBUILD RUN apt update && apt install python3-pip -y

ONBUILD RUN pip install -r requirements.txt && rm -rf requirements.txt

ONBUILD CMD ["python", "-m", "app"]