FROM python:3.12

SHELL ["/bin/bash", "-c"]

WORKDIR /app

COPY requirements.txt .

COPY ./app ./app

RUN apt update && apt install python3-pip -y

RUN pip install -r requirements.txt

CMD ["python", "-m", "app"]